Repository Group-20-ADP/School_Management, pull requests merged in 2022-06, with the labels that each got.

#9 pom altered
  pom.xml
Labels: enhancement

#10 Employee and Name Domain
  src/main/java/za/ac/cput/school_management/domain/Employee.java
  src/main/java/za/ac/cput/school_management/domain/Name.java
Labels: enhancement

#12 Completed Domain Model -> EmployeeAddress, Address
  src/main/java/za/ac/cput/school_management/domain/Address.java
  src/main/java/za/ac/cput/school_management/domain/EmployeeAddress.java
Labels: enhancement

#17 Employee and Name Factory
  src/main/java/za/ac/cput/school_management/domain/Employee.java
  src/main/java/za/ac/cput/school_management/domain/Name.java
  src/main/java/za/ac/cput/school_management/domain/StudentAddress.java
  src/main/java/za/ac/cput/school_management/factory/EmployeeFactory.java
  src/main/java/za/ac/cput/school_management/factory/NameFactory.java
  src/main/java/za/ac/cput/school_management/utility/Helper.java
  src/test/java/za/ac/cput/school_management/factory/EmployeeFactoryTest.java
  src/test/java/za/ac/cput/school_management/factory/NameFactoryTest.java
Labels: enhancement

#28 finished domain class for Student
  src/main/java/za/ac/cput/school_management/domain/Student.java
Labels: enhancement

#33 Added City Domain
  src/main/java/za/ac/cput/school_management/domain/City.java
Labels: enhancement

#34 Completed Repository -> EmployeeAddress
  src/main/java/za/ac/cput/school_management/repository/IEmployeeAddressRepository.java
Labels: enhancement

#35 "Finished with Student Repository"
  src/main/java/za/ac/cput/school_management/repository/IStudentRepository.java
Labels: enhancement

#36 Completed Service and Related Tests -> EmployeeAddress
  .gitignore
  src/main/java/za/ac/cput/school_management/domain/EmployeeAddress.java
  src/main/java/za/ac/cput/school_management/service/IEmployeeAddressService.java
  src/main/java/za/ac/cput/school_management/service/implementation/EmployeeAddressImpl.java
  src/main/resources/application.properties
  src/test/java/za/ac/cput/school_management/service/implementation/EmployeeAddressImplTest.java
Labels: enhancement

#37 Employee Service
  src/main/java/za/ac/cput/school_management/domain/StudentAddress.java
  src/main/java/za/ac/cput/school_management/exception/ResourceNotFoundException.java
  src/main/java/za/ac/cput/school_management/repository/EmployeeRepository.java
  src/main/java/za/ac/cput/school_management/service/EmployeeService.java
Labels: enhancement

#44 Minor Changes
  src/main/java/za/ac/cput/school_management/domain/Employee.java
Labels: enhancement

#46 Q6: Find By Email Employee
  src/main/java/za/ac/cput/school_management/repository/EmployeeRepository.java
  src/main/java/za/ac/cput/school_management/service/EmployeeService.java
Labels: enhancement

#48 Exposed APi endpoints in controller
  src/main/java/za/ac/cput/school_management/controller/EmployeeController.java
Labels: enhancement

#49 Minor changes to student
  src/main/java/za/ac/cput/school_management/domain/Student.java
Labels: enhancement

#55 Fixed Merge Conflicts
  dummydata.sql
  src/main/java/za/ac/cput/school_management/SchoolManagementApplication.java
  src/main/java/za/ac/cput/school_management/controller/EmployeeController.java
  src/main/java/za/ac/cput/school_management/domain/Employee.java
  src/main/java/za/ac/cput/school_management/domain/EmployeeAddress.java
  src/main/java/za/ac/cput/school_management/domain/Student.java
  src/main/java/za/ac/cput/school_management/domain/StudentAddress.java
  src/main/java/za/ac/cput/school_management/domain/valueobjects/Address.java
  src/main/java/za/ac/cput/school_management/domain/valueobjects/Name.java
  src/main/java/za/ac/cput/school_management/factory/AddressFactory.java
  src/main/java/za/ac/cput/school_management/factory/EmployeeAddressFactory.java
  src/main/java/za/ac/cput/school_management/factory/EmployeeFactory.java
  src/main/java/za/ac/cput/school_management/factory/NameFactory.java
  src/main/java/za/ac/cput/school_management/factory/StudentFactory.java
  src/main/java/za/ac/cput/school_management/service/IEmployeeService.java
  src/main/java/za/ac/cput/school_management/service/IService.java
  src/main/java/za/ac/cput/school_management/service/implementation/EmployeeService.java
  src/main/resources/application.properties
  src/test/java/za/ac/cput/school_management/factory/AddressFactoryTest.java
Labels: enhancement

#57 Finished Employee Controller and Component
  src/main/java/za/ac/cput/school_management/controller/EmployeeController.java
  src/main/java/za/ac/cput/school_management/domain/Employee.java
  src/main/java/za/ac/cput/school_management/factory/EmployeeFactory.java
  src/main/java/za/ac/cput/school_management/repository/EmployeeRepository.java
  src/main/java/za/ac/cput/school_management/service/IEmployeeService.java
  src/main/java/za/ac/cput/school_management/service/IService.java
  src/main/java/za/ac/cput/school_management/service/implementation/EmployeeService.java
  src/test/java/za/ac/cput/school_management/factory/EmployeeFactoryTest.java
Labels: enhancement

#61 Refactor Country
  src/main/java/za/ac/cput/school_management/controller/CountryController.java
  src/main/java/za/ac/cput/school_management/domain/Country.java
  src/main/java/za/ac/cput/school_management/factory/CountryFactory.java
  src/main/java/za/ac/cput/school_management/repository/CountryRepository.java
  src/main/java/za/ac/cput/school_management/service/Country/ICountryService.java
  src/main/java/za/ac/cput/school_management/service/Country/Impl/CountryServiceImpl.java
  src/test/java/za/ac/cput/school_management/controller/CountryControllerTest.java
  src/test/java/za/ac/cput/school_management/factory/CountryFactoryTest.java
  src/test/java/za/ac/cput/school_management/service/Country/Impl/CountryServiceImplTest.java
Labels: enhancement

#62 City Entities refactored
  src/main/java/za/ac/cput/school_management/controller/CityController.java
  src/main/java/za/ac/cput/school_management/domain/City.java
  src/main/java/za/ac/cput/school_management/factory/CityFactory.java
  src/main/java/za/ac/cput/school_management/repository/CityRepository.java
  src/main/java/za/ac/cput/school_management/service/City/ICityService.java
  src/main/java/za/ac/cput/school_management/service/City/Impl/CityServiceImpl.java
  src/test/java/za/ac/cput/school_management/controller/CityControllerTest.java
  src/test/java/za/ac/cput/school_management/factory/CityFactoryTest.java
Labels: enhancement

#63 Finalized Employee
  src/main/java/za/ac/cput/school_management/controller/EmployeeController.java
  src/main/java/za/ac/cput/school_management/controller/StudentController.java
  src/main/java/za/ac/cput/school_management/domain/Employee.java
  src/main/java/za/ac/cput/school_management/domain/valueobjects/Name.java
  src/main/java/za/ac/cput/school_management/factory/EmployeeFactory.java
  src/main/java/za/ac/cput/school_management/factory/NameFactory.java
  src/main/java/za/ac/cput/school_management/repository/EmployeeRepository.java
  src/main/java/za/ac/cput/school_management/service/Employee/IEmployeeService.java
  src/main/java/za/ac/cput/school_management/service/Employee/Impl/EmployeeService.java
  src/main/java/za/ac/cput/school_management/service/Student/Impl/IStudentServiceImpl.java
Labels: enhancement

#65 "update student entity"
  src/main/java/za/ac/cput/school_management/domain/Student.java
  src/main/java/za/ac/cput/school_management/factory/StudentFactory.java
  src/main/java/za/ac/cput/school_management/repository/StudentRepository.java
  src/main/java/za/ac/cput/school_management/service/Student/IStudentService.java
  src/main/java/za/ac/cput/school_management/service/Student/Impl/IStudentServiceImpl.java
  src/main/java/za/ac/cput/school_management/service/Student/Impl/StudentServiceImpl.java
Labels: enhancement

#66 Student factory test
  src/test/java/za/ac/cput/school_management/factory/StudentFactoryTest.java
Labels: enhancement

#67 Fixed Student FindByID
  src/main/java/za/ac/cput/school_management/controller/StudentController.java
  src/test/java/za/ac/cput/school_management/factory/EmployeeFactoryTest.java
Labels: bug

#68 Initial commit
  src/main/java/za/ac/cput/school_management/controller/StudentAddressController.java
  src/main/java/za/ac/cput/school_management/domain/StudentAddress.java
  src/main/java/za/ac/cput/school_management/factory/StudentAddressFactory.java
  src/main/java/za/ac/cput/school_management/repository/StudentAddressRepository.java
  src/main/java/za/ac/cput/school_management/service/StudentAddress/IStudentAddressService.java
  src/main/java/za/ac/cput/school_management/service/StudentAddress/impl/StudentAddressServiceImpl.java
Labels: bug, enhancement

#69 Added City Services tests and made a few changes to neaten my code
  src/main/java/za/ac/cput/school_management/controller/CityController.java
  src/main/java/za/ac/cput/school_management/service/City/Impl/CityServiceImpl.java
  src/test/java/za/ac/cput/school_management/controller/CityControllerTest.java
  src/test/java/za/ac/cput/school_management/factory/CityFactoryTest.java
  src/test/java/za/ac/cput/school_management/service/City/Impl/CityServiceImplTest.java
Labels: enhancement

#70 added readme and test class for employee
  BLANK_README.md
  CHANGELOG.md
  images/logo.png
  images/screenshot.png
  src/test/java/za/ac/cput/school_management/service/Employee/Impl/EmployeeServiceTest.java
Labels: bug

#77 Final Words
  README.md
  src/main/java/za/ac/cput/school_management/domain/valueobjects/Name.java
  src/test/java/za/ac/cput/school_management/service/Employee/Impl/EmployeeServiceTest.java
Labels: enhancement
